### ISSUE TITLE
Can't install on F22

### ISSUE THREAD

**Issue by KAMiKAZOW** [RussianFedora/aegisub#1]
"Error: nothing provides libboost_chrono.so.1.55.0()(64bit) needed by aegisub-3.2.2-1.fc22.R.x86_64"

**Comment by Vascom** [comment]
Will be updated soon.

**Comment by isage** [comment]
@Vascom i see you've taken it.
Also, dist-rfr23-devel is deprecated, you should use dist-rfr23

**Comment by Vascom** [comment]
@isage If want you can take it back because it has errors in compiling http://koji.russianfedora.pro/kojifiles/work/tasks/5948/55948/build.log

**Comment by isage** [comment]
@Vascom okay.

**Comment by isage** [comment]
Sorry it's taking so long, our koji is a little cranky.
